/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.fast;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RYAN
 */
public class RENTAL extends javax.swing.JFrame {
    private DefaultTableModel model;

    
    harga h = new harga();
    /**
     * Creates new form RENTAL
     */
    public RENTAL() {
        initComponents();
        model = new DefaultTableModel ( );
         tabelmobil.setModel(model);
         model.addColumn("Merk Mobil");
         model.addColumn("Jenis Mobil");
         model.addColumn("Kategori Mobil");
         model.addColumn("Tahun Mobil");
         model.addColumn("Nomor Polisi");
         model.addColumn("Harga Mobil");
        
         try{
            // Mengambil data dari database
            koneksi db = new koneksi();
            ResultSet res;
            String sql;
            
            sql = "SELECT * FROM datamobil";
            res = db.getData(sql);

            while (res.next()){
                // Mengambil data dari database berdasarkan nama kolom pada tabel
                // Lalu di tampilkan ke dalam JTable
                model.addRow(new Object[]{
                res.getString("merkMobil"),
                res.getString("jenisMobil"),
                res.getString("kategoriMobil"),
                res.getString("tahunMobil"),
                res.getString("nopolMobil"),
                res.getInt("hargaMobil")
                });
            }
        }catch (Exception e){
        }




    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Rental = new javax.swing.JTabbedPane();
        PesanMobil = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        merk = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pesan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tahun = new javax.swing.JLabel();
        nopolisi = new javax.swing.JLabel();
        check = new javax.swing.JButton();
        jenis = new javax.swing.JLabel();
        yaSopir = new javax.swing.JRadioButton();
        tidakSopir = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelmobil = new javax.swing.JTable();
        okMerk = new javax.swing.JButton();
        kategori = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PesanMobil.setBackground(new java.awt.Color(0, 0, 0));
        PesanMobil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MERK MOBIL");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("JENIS MOBIL");

        merk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-PILIH-", "TOYOTA", "HONDA", "FERRARI", "NISSAN", "MITSUBISHI", "LAMBORGHINI" }));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TAHUN");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NO POLISI");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("KATEGORI");

        pesan.setText("PESAN");
        pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SUPIR");

        tahun.setBackground(new java.awt.Color(255, 255, 255));
        tahun.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        tahun.setForeground(new java.awt.Color(255, 255, 255));
        tahun.setText("-");

        nopolisi.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        nopolisi.setForeground(new java.awt.Color(255, 255, 255));
        nopolisi.setText("-");

        check.setText("CHECK");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        jenis.setForeground(new java.awt.Color(255, 255, 255));
        jenis.setText("-");

        buttonGroup1.add(yaSopir);
        yaSopir.setForeground(new java.awt.Color(255, 255, 255));
        yaSopir.setText("Ya");

        buttonGroup1.add(tidakSopir);
        tidakSopir.setForeground(new java.awt.Color(255, 255, 255));
        tidakSopir.setText("Tidak");

        tabelmobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelmobil);

        okMerk.setText("OK");
        okMerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okMerkActionPerformed(evt);
            }
        });

        kategori.setForeground(new java.awt.Color(255, 255, 255));
        kategori.setText("-");

        javax.swing.GroupLayout PesanMobilLayout = new javax.swing.GroupLayout(PesanMobil);
        PesanMobil.setLayout(PesanMobilLayout);
        PesanMobilLayout.setHorizontalGroup(
            PesanMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesanMobilLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(PesanMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addGap(66, 66, 66)
                .addGroup(PesanMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PesanMobilLayout.createSequentialGroup()
                        .addComponent(merk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(okMerk))
                    .addGroup(PesanMobilLayout.createSequentialGroup()
                        .addComponent(yaSopir)
                        .addGap(60, 60, 60)
                        .addComponent(tidakSopir))
                    .addComponent(jenis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kategori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nopolisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tahun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PesanMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pesan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
            .addGroup(PesanMobilLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        PesanMobilLayout.setVerticalGroup(
            PesanMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesanMobilLayout.createSequentialGroup()
                .addGroup(PesanMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PesanMobilLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(PesanMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(merk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(okMerk))
                        .addGap(21, 21, 21)
                        .addGroup(PesanMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jenis))
                        .addGap(18, 18, 18)
                        .addGroup(PesanMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(kategori))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(PesanMobilLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pesan, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)))
                .addGroup(PesanMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PesanMobilLayout.createSequentialGroup()
                        .addGroup(PesanMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tidakSopir)
                            .addGroup(PesanMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(yaSopir)
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)
                        .addGroup(PesanMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tahun))
                        .addGap(18, 18, 18)
                        .addGroup(PesanMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(nopolisi))))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );

        Rental.addTab("                                                                                                      PESAN MOBIL                                                                                                               ", PesanMobil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Rental, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Rental, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        try {
            koneksi db = new koneksi();
            String a = merk.getSelectedItem().toString();
            ResultSet rs = db.getData("SELECT * FROM datamobil where merkMobil = '"+a+"'");
            
            long b = 0;
            while (rs.next()){
                b = rs.getInt("hargaMobil");
                
            }
            if (yaSopir.isSelected()){
                b += 50000;
                JOptionPane.showMessageDialog(null, "Harga Mobil + Supir yang harus anda bayar = "+b);
            }
            else{
                JOptionPane.showMessageDialog(null, "Harga Mobil yang harus anda bayar = "+b);
            }
        
            
            
            
        
        
        
        } catch (SQLException ex) {
            Logger.getLogger(RENTAL.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_checkActionPerformed

    private void pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanActionPerformed
        try {
            
            
            
            koneksi db = new koneksi();
            String a = merk.getSelectedItem().toString();
            ResultSet rs = db.getData("SELECT * FROM datamobil where merkMobil = '"+a+"'");
            
            long b = 0;
            while (rs.next()){
                b = rs.getInt("hargaMobil");
                
            }
            
            
            if (yaSopir.isSelected()){
                db.Query("delete from invoice");
                db.Query("INSERT INTO invoice VALUES('"+b+"', 50000)");
                b += 50000;
            }
            else{
                db.Query("delete from invoice");
                db.Query("INSERT INTO invoice VALUES('"+b+"', 0)");
            }
            
            h.setHargaTotal(b);
            rs = db.getData("SELECT * FROM login");
            String z = null;
            while(rs.next()){
                z = rs.getString("userlogin");
                
            }
            rs = db.getData("SELECT * FROM datauser WHERE usernameUser = '"+z+"'");
            while(rs.next()){
                z = rs.getString("namaUser");
            }
            db.Query("INSERT INTO pesanan VALUES('"+z+"','"+a+"','"+jenis.getText()+"','"+kategori.getText()+"','"+tahun.getText()+"','"+nopolisi.getText()+"')");
            FINISH finish = new FINISH();
            finish.setVisible(true);
            this.dispose();
//            db.Query("insert into invoice values ('"+h.getHargaTotal()+"')");
        } catch (SQLException ex) {
            Logger.getLogger(RENTAL.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_pesanActionPerformed

    private void okMerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okMerkActionPerformed
        try {
            koneksi db = new koneksi();
            String a = merk.getSelectedItem().toString();
            ResultSet rs = db.getData("SELECT * FROM datamobil where merkMobil = '"+a+"'");
            while (rs.next()){
                jenis.setText(rs.getString("jenisMobil"));
                kategori.setText(rs.getString("kategoriMobil"));
                tahun.setText(rs.getString("tahunMobil"));
                nopolisi.setText(rs.getString("nopolMobil"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(RENTAL.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_okMerkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RENTAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RENTAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RENTAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RENTAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RENTAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PesanMobil;
    private javax.swing.JTabbedPane Rental;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton check;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jenis;
    private javax.swing.JLabel kategori;
    private javax.swing.JComboBox<String> merk;
    private javax.swing.JLabel nopolisi;
    private javax.swing.JButton okMerk;
    private javax.swing.JButton pesan;
    private javax.swing.JTable tabelmobil;
    private javax.swing.JLabel tahun;
    private javax.swing.JRadioButton tidakSopir;
    private javax.swing.JRadioButton yaSopir;
    // End of variables declaration//GEN-END:variables

    private void reset(JComboBox<String> merk) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
